server:
  port: 9002
spring:
  application:
    name: leadnews-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.85.143:3306/leadnews_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.85.143:8848
  kafka:
    bootstrap-servers: 192.168.85.143:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis-plus:
  # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.user.entity
  configuration:
    # sql输出到控制台,方便开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  service:
    disable-global-transaction: false
    grouplist:
    - 192.168.85.143:8091
    vgroup-mapping:
      leadnews-user_tx_group: default
  tx-service-group: leadnews-user_tx_group
topic:
  followBehaviorTopic: follow_behavior_topic
